-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 18:51:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema goods
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema goods
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema goods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goods` DEFAULT CHARACTER SET utf8;
-- -----------------------------------------------------
-- Schema goods
-- -----------------------------------------------------
USE `goods` ;

-- -----------------------------------------------------
-- Table `goods`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goods`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `price` FLOAT(2) NOT NULL,
  `description` TEXT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category1`
  FOREIGN KEY (`category_id`)
  REFERENCES `goods`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goods`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods`.`customer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goods`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_order_customer1`
  FOREIGN KEY (`customer_id`)
  REFERENCES `goods`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goods`.`basket_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goods`.`basket_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` INT UNSIGNED NOT NULL,
  `price` FLOAT(2) NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_basket_item_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_basket_item_customer1`
  FOREIGN KEY (`customer_id`)
  REFERENCES `goods`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'goods'@'localhost' IDENTIFIED BY 'goods';
GRANT ALL PRIVILEGES ON goods.* TO 'goods'@'localhost';
FLUSH PRIVILEGES;